# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20170604_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='logo',
            field=models.FileField(upload_to=''),
        ),
    ]
